// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bio01_cpp
NumericVector bio01_cpp(NumericMatrix tas);
RcppExport SEXP _xclim_bio01_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio01_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio02_cpp
NumericVector bio02_cpp(NumericMatrix tasmax, NumericMatrix tasmin);
RcppExport SEXP _xclim_bio02_cpp(SEXP tasmaxSEXP, SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio02_cpp(tasmax, tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio03_cpp
NumericVector bio03_cpp(NumericMatrix tasmax, NumericMatrix tasmin);
RcppExport SEXP _xclim_bio03_cpp(SEXP tasmaxSEXP, SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio03_cpp(tasmax, tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio04_cpp
NumericVector bio04_cpp(NumericMatrix tas);
RcppExport SEXP _xclim_bio04_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio04_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio05_cpp
NumericVector bio05_cpp(NumericMatrix tasmax);
RcppExport SEXP _xclim_bio05_cpp(SEXP tasmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(bio05_cpp(tasmax));
    return rcpp_result_gen;
END_RCPP
}
// bio06_cpp
NumericVector bio06_cpp(NumericMatrix tasmin);
RcppExport SEXP _xclim_bio06_cpp(SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio06_cpp(tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio07_cpp
NumericVector bio07_cpp(NumericMatrix tasmax, NumericMatrix tasmin);
RcppExport SEXP _xclim_bio07_cpp(SEXP tasmaxSEXP, SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio07_cpp(tasmax, tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio08_cpp
NumericVector bio08_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _xclim_bio08_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio08_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bio09_cpp
NumericVector bio09_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _xclim_bio09_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio09_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bio10_cpp
NumericVector bio10_cpp(NumericMatrix tas);
RcppExport SEXP _xclim_bio10_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio10_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio11_cpp
NumericVector bio11_cpp(NumericMatrix tas);
RcppExport SEXP _xclim_bio11_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio11_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio12_cpp
NumericVector bio12_cpp(NumericMatrix pr);
RcppExport SEXP _xclim_bio12_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio12_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio13_cpp
NumericVector bio13_cpp(NumericMatrix pr);
RcppExport SEXP _xclim_bio13_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio13_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio14_cpp
NumericVector bio14_cpp(NumericMatrix pr);
RcppExport SEXP _xclim_bio14_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio14_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio15_cpp
NumericVector bio15_cpp(NumericMatrix pr);
RcppExport SEXP _xclim_bio15_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio15_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio16_cpp
NumericVector bio16_cpp(NumericMatrix pr);
RcppExport SEXP _xclim_bio16_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio16_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio17_cpp
NumericVector bio17_cpp(NumericMatrix pr);
RcppExport SEXP _xclim_bio17_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio17_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio18_cpp
NumericVector bio18_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _xclim_bio18_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio18_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bio19_cpp
NumericVector bio19_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _xclim_bio19_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio19_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_cpp
NumericMatrix bioclim_cpp(NumericMatrix tas, NumericMatrix tasmax, NumericMatrix tasmin, NumericMatrix pr, int ncores);
RcppExport SEXP _xclim_bioclim_cpp(SEXP tasSEXP, SEXP tasmaxSEXP, SEXP tasminSEXP, SEXP prSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_cpp(tas, tasmax, tasmin, pr, ncores));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_new
SEXP bioclim_model_new(Rcpp::NumericVector tas, Rcpp::NumericVector tasmax, Rcpp::NumericVector tasmin, Rcpp::NumericVector pr);
RcppExport SEXP _xclim_bioclim_model_new(SEXP tasSEXP, SEXP tasmaxSEXP, SEXP tasminSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tasmin(tasminSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_new(tas, tasmax, tasmin, pr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_is_null
bool bioclim_model_is_null(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_is_null(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_is_null(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio01
double bioclim_model_bio01(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio01(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio01(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio02
double bioclim_model_bio02(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio02(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio02(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio03
double bioclim_model_bio03(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio03(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio03(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio04
double bioclim_model_bio04(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio04(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio04(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio05
double bioclim_model_bio05(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio05(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio05(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio06
double bioclim_model_bio06(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio06(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio06(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio07
double bioclim_model_bio07(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio07(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio07(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio08
double bioclim_model_bio08(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio08(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio08(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio09
double bioclim_model_bio09(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio09(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio09(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio10
double bioclim_model_bio10(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio10(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio10(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio11
double bioclim_model_bio11(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio11(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio11(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio12
double bioclim_model_bio12(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio12(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio12(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio13
double bioclim_model_bio13(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio13(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio13(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio14
double bioclim_model_bio14(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio14(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio14(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio15
double bioclim_model_bio15(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio15(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio15(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio16
double bioclim_model_bio16(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio16(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio16(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio17
double bioclim_model_bio17(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio17(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio17(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio18
double bioclim_model_bio18(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio18(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio18(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio19
double bioclim_model_bio19(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_bio19(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio19(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_compute
Rcpp::NumericVector bioclim_model_compute(SEXP ptr);
RcppExport SEXP _xclim_bioclim_model_compute(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_compute(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_xt
NumericMatrix bioclim_xt(NumericMatrix tas, NumericMatrix tasmax, NumericMatrix tasmin, NumericMatrix pr, int ncores);
RcppExport SEXP _xclim_bioclim_xt(SEXP tasSEXP, SEXP tasmaxSEXP, SEXP tasminSEXP, SEXP prSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_xt(tas, tasmax, tasmin, pr, ncores));
    return rcpp_result_gen;
END_RCPP
}
// era5_t2m_to_monthly_cpp
List era5_t2m_to_monthly_cpp(NumericMatrix hourly, int n_days, bool to_celsius, int ncores);
RcppExport SEXP _xclim_era5_t2m_to_monthly_cpp(SEXP hourlySEXP, SEXP n_daysSEXP, SEXP to_celsiusSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type hourly(hourlySEXP);
    Rcpp::traits::input_parameter< int >::type n_days(n_daysSEXP);
    Rcpp::traits::input_parameter< bool >::type to_celsius(to_celsiusSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(era5_t2m_to_monthly_cpp(hourly, n_days, to_celsius, ncores));
    return rcpp_result_gen;
END_RCPP
}
// era5_tp_to_monthly_cpp
NumericVector era5_tp_to_monthly_cpp(NumericMatrix hourly, int ncores);
RcppExport SEXP _xclim_era5_tp_to_monthly_cpp(SEXP hourlySEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type hourly(hourlySEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(era5_tp_to_monthly_cpp(hourly, ncores));
    return rcpp_result_gen;
END_RCPP
}
// era5_to_monthly_cpp
List era5_to_monthly_cpp(NumericMatrix hourly_t2m, NumericMatrix hourly_tp, int n_days, bool to_celsius, int ncores);
RcppExport SEXP _xclim_era5_to_monthly_cpp(SEXP hourly_t2mSEXP, SEXP hourly_tpSEXP, SEXP n_daysSEXP, SEXP to_celsiusSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type hourly_t2m(hourly_t2mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type hourly_tp(hourly_tpSEXP);
    Rcpp::traits::input_parameter< int >::type n_days(n_daysSEXP);
    Rcpp::traits::input_parameter< bool >::type to_celsius(to_celsiusSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(era5_to_monthly_cpp(hourly_t2m, hourly_tp, n_days, to_celsius, ncores));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_bioclim_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_xclim_bio01_cpp", (DL_FUNC) &_xclim_bio01_cpp, 1},
    {"_xclim_bio02_cpp", (DL_FUNC) &_xclim_bio02_cpp, 2},
    {"_xclim_bio03_cpp", (DL_FUNC) &_xclim_bio03_cpp, 2},
    {"_xclim_bio04_cpp", (DL_FUNC) &_xclim_bio04_cpp, 1},
    {"_xclim_bio05_cpp", (DL_FUNC) &_xclim_bio05_cpp, 1},
    {"_xclim_bio06_cpp", (DL_FUNC) &_xclim_bio06_cpp, 1},
    {"_xclim_bio07_cpp", (DL_FUNC) &_xclim_bio07_cpp, 2},
    {"_xclim_bio08_cpp", (DL_FUNC) &_xclim_bio08_cpp, 2},
    {"_xclim_bio09_cpp", (DL_FUNC) &_xclim_bio09_cpp, 2},
    {"_xclim_bio10_cpp", (DL_FUNC) &_xclim_bio10_cpp, 1},
    {"_xclim_bio11_cpp", (DL_FUNC) &_xclim_bio11_cpp, 1},
    {"_xclim_bio12_cpp", (DL_FUNC) &_xclim_bio12_cpp, 1},
    {"_xclim_bio13_cpp", (DL_FUNC) &_xclim_bio13_cpp, 1},
    {"_xclim_bio14_cpp", (DL_FUNC) &_xclim_bio14_cpp, 1},
    {"_xclim_bio15_cpp", (DL_FUNC) &_xclim_bio15_cpp, 1},
    {"_xclim_bio16_cpp", (DL_FUNC) &_xclim_bio16_cpp, 1},
    {"_xclim_bio17_cpp", (DL_FUNC) &_xclim_bio17_cpp, 1},
    {"_xclim_bio18_cpp", (DL_FUNC) &_xclim_bio18_cpp, 2},
    {"_xclim_bio19_cpp", (DL_FUNC) &_xclim_bio19_cpp, 2},
    {"_xclim_bioclim_cpp", (DL_FUNC) &_xclim_bioclim_cpp, 5},
    {"_xclim_bioclim_model_new", (DL_FUNC) &_xclim_bioclim_model_new, 4},
    {"_xclim_bioclim_model_is_null", (DL_FUNC) &_xclim_bioclim_model_is_null, 1},
    {"_xclim_bioclim_model_bio01", (DL_FUNC) &_xclim_bioclim_model_bio01, 1},
    {"_xclim_bioclim_model_bio02", (DL_FUNC) &_xclim_bioclim_model_bio02, 1},
    {"_xclim_bioclim_model_bio03", (DL_FUNC) &_xclim_bioclim_model_bio03, 1},
    {"_xclim_bioclim_model_bio04", (DL_FUNC) &_xclim_bioclim_model_bio04, 1},
    {"_xclim_bioclim_model_bio05", (DL_FUNC) &_xclim_bioclim_model_bio05, 1},
    {"_xclim_bioclim_model_bio06", (DL_FUNC) &_xclim_bioclim_model_bio06, 1},
    {"_xclim_bioclim_model_bio07", (DL_FUNC) &_xclim_bioclim_model_bio07, 1},
    {"_xclim_bioclim_model_bio08", (DL_FUNC) &_xclim_bioclim_model_bio08, 1},
    {"_xclim_bioclim_model_bio09", (DL_FUNC) &_xclim_bioclim_model_bio09, 1},
    {"_xclim_bioclim_model_bio10", (DL_FUNC) &_xclim_bioclim_model_bio10, 1},
    {"_xclim_bioclim_model_bio11", (DL_FUNC) &_xclim_bioclim_model_bio11, 1},
    {"_xclim_bioclim_model_bio12", (DL_FUNC) &_xclim_bioclim_model_bio12, 1},
    {"_xclim_bioclim_model_bio13", (DL_FUNC) &_xclim_bioclim_model_bio13, 1},
    {"_xclim_bioclim_model_bio14", (DL_FUNC) &_xclim_bioclim_model_bio14, 1},
    {"_xclim_bioclim_model_bio15", (DL_FUNC) &_xclim_bioclim_model_bio15, 1},
    {"_xclim_bioclim_model_bio16", (DL_FUNC) &_xclim_bioclim_model_bio16, 1},
    {"_xclim_bioclim_model_bio17", (DL_FUNC) &_xclim_bioclim_model_bio17, 1},
    {"_xclim_bioclim_model_bio18", (DL_FUNC) &_xclim_bioclim_model_bio18, 1},
    {"_xclim_bioclim_model_bio19", (DL_FUNC) &_xclim_bioclim_model_bio19, 1},
    {"_xclim_bioclim_model_compute", (DL_FUNC) &_xclim_bioclim_model_compute, 1},
    {"_xclim_bioclim_xt", (DL_FUNC) &_xclim_bioclim_xt, 5},
    {"_xclim_era5_t2m_to_monthly_cpp", (DL_FUNC) &_xclim_era5_t2m_to_monthly_cpp, 4},
    {"_xclim_era5_tp_to_monthly_cpp", (DL_FUNC) &_xclim_era5_tp_to_monthly_cpp, 2},
    {"_xclim_era5_to_monthly_cpp", (DL_FUNC) &_xclim_era5_to_monthly_cpp, 5},
    {"_rcpp_module_boot_bioclim_mod", (DL_FUNC) &_rcpp_module_boot_bioclim_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_xclim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
