# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute BIO01 (Mean Annual Temperature) for a raster block
#'
#' @param tas Numeric matrix with 12 columns (one per month); rows are pixels.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio01_cpp <- function(tas) {
    .Call(`_xclim_bio01_cpp`, tas)
}

#' Compute BIO02 (Mean Diurnal Range) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio02_cpp <- function(tasmax, tasmin) {
    .Call(`_xclim_bio02_cpp`, tasmax, tasmin)
}

#' Compute BIO03 (Isothermality) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel (NaN where BIO07 == 0).
#' @keywords internal
bio03_cpp <- function(tasmax, tasmin) {
    .Call(`_xclim_bio03_cpp`, tasmax, tasmin)
}

#' Compute BIO04 (Temperature Seasonality) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio04_cpp <- function(tas) {
    .Call(`_xclim_bio04_cpp`, tas)
}

#' Compute BIO05 (Max Temperature of Warmest Month) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio05_cpp <- function(tasmax) {
    .Call(`_xclim_bio05_cpp`, tasmax)
}

#' Compute BIO06 (Min Temperature of Coldest Month) for a raster block
#'
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio06_cpp <- function(tasmin) {
    .Call(`_xclim_bio06_cpp`, tasmin)
}

#' Compute BIO07 (Temperature Annual Range) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio07_cpp <- function(tasmax, tasmin) {
    .Call(`_xclim_bio07_cpp`, tasmax, tasmin)
}

#' Compute BIO08 (Mean Temperature of Wettest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio08_cpp <- function(tas, pr) {
    .Call(`_xclim_bio08_cpp`, tas, pr)
}

#' Compute BIO09 (Mean Temperature of Driest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio09_cpp <- function(tas, pr) {
    .Call(`_xclim_bio09_cpp`, tas, pr)
}

#' Compute BIO10 (Mean Temperature of Warmest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio10_cpp <- function(tas) {
    .Call(`_xclim_bio10_cpp`, tas)
}

#' Compute BIO11 (Mean Temperature of Coldest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio11_cpp <- function(tas) {
    .Call(`_xclim_bio11_cpp`, tas)
}

#' Compute BIO12 (Annual Precipitation) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio12_cpp <- function(pr) {
    .Call(`_xclim_bio12_cpp`, pr)
}

#' Compute BIO13 (Precipitation of Wettest Month) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio13_cpp <- function(pr) {
    .Call(`_xclim_bio13_cpp`, pr)
}

#' Compute BIO14 (Precipitation of Driest Month) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio14_cpp <- function(pr) {
    .Call(`_xclim_bio14_cpp`, pr)
}

#' Compute BIO15 (Precipitation Seasonality) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel (NaN where mean precip == 0).
#' @keywords internal
bio15_cpp <- function(pr) {
    .Call(`_xclim_bio15_cpp`, pr)
}

#' Compute BIO16 (Precipitation of Wettest Quarter) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio16_cpp <- function(pr) {
    .Call(`_xclim_bio16_cpp`, pr)
}

#' Compute BIO17 (Precipitation of Driest Quarter) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio17_cpp <- function(pr) {
    .Call(`_xclim_bio17_cpp`, pr)
}

#' Compute BIO18 (Precipitation of Warmest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio18_cpp <- function(tas, pr) {
    .Call(`_xclim_bio18_cpp`, tas, pr)
}

#' Compute BIO19 (Precipitation of Coldest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio19_cpp <- function(tas, pr) {
    .Call(`_xclim_bio19_cpp`, tas, pr)
}

#' Compute all 19 bioclimatic variables for a raster block
#'
#' @param tas    Numeric matrix (pixels x 12): monthly mean temperature.
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @param pr     Numeric matrix (pixels x 12): monthly precipitation.
#' @param ncores Integer: number of OpenMP threads (default 1).
#' @return Numeric matrix (pixels x 19) with one column per variable
#'   (bio01..bio19), named accordingly. Rows with any NA input are returned
#'   as all-NA.
#' @keywords internal
bioclim_cpp <- function(tas, tasmax, tasmin, pr, ncores = 1L) {
    .Call(`_xclim_bioclim_cpp`, tas, tasmax, tasmin, pr, ncores)
}

#' Create a new C++ BioclimModel and return an external pointer
#'
#' @param tas    Numeric vector of length 12.
#' @param tasmax Numeric vector of length 12.
#' @param tasmin Numeric vector of length 12.
#' @param pr     Numeric vector of length 12.
#' @return An external pointer wrapping a \code{BioclimModel} C++ object.
#' @keywords internal
bioclim_model_new <- function(tas, tasmax, tasmin, pr) {
    .Call(`_xclim_bioclim_model_new`, tas, tasmax, tasmin, pr)
}

#' Test whether the C++ pointer is null
#' @param ptr An external pointer.
#' @return Logical scalar.
#' @keywords internal
bioclim_model_is_null <- function(ptr) {
    .Call(`_xclim_bioclim_model_is_null`, ptr)
}

#' @keywords internal
bioclim_model_bio01 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio01`, ptr)
}

#' @keywords internal
bioclim_model_bio02 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio02`, ptr)
}

#' @keywords internal
bioclim_model_bio03 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio03`, ptr)
}

#' @keywords internal
bioclim_model_bio04 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio04`, ptr)
}

#' @keywords internal
bioclim_model_bio05 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio05`, ptr)
}

#' @keywords internal
bioclim_model_bio06 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio06`, ptr)
}

#' @keywords internal
bioclim_model_bio07 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio07`, ptr)
}

#' @keywords internal
bioclim_model_bio08 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio08`, ptr)
}

#' @keywords internal
bioclim_model_bio09 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio09`, ptr)
}

#' @keywords internal
bioclim_model_bio10 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio10`, ptr)
}

#' @keywords internal
bioclim_model_bio11 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio11`, ptr)
}

#' @keywords internal
bioclim_model_bio12 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio12`, ptr)
}

#' @keywords internal
bioclim_model_bio13 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio13`, ptr)
}

#' @keywords internal
bioclim_model_bio14 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio14`, ptr)
}

#' @keywords internal
bioclim_model_bio15 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio15`, ptr)
}

#' @keywords internal
bioclim_model_bio16 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio16`, ptr)
}

#' @keywords internal
bioclim_model_bio17 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio17`, ptr)
}

#' @keywords internal
bioclim_model_bio18 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio18`, ptr)
}

#' @keywords internal
bioclim_model_bio19 <- function(ptr) {
    .Call(`_xclim_bioclim_model_bio19`, ptr)
}

#' Compute all 19 bioclimatic variables from the C++ object
#' @param ptr An external pointer to a \code{BioclimModel} C++ object.
#' @return Named numeric vector of length 19.
#' @keywords internal
bioclim_model_compute <- function(ptr) {
    .Call(`_xclim_bioclim_model_compute`, ptr)
}

#' Compute all 19 bioclimatic variables (vectorized, zero-copy bridge)
#'
#' A faster alternative to \code{bioclim_cpp()} that uses whole-array
#' vectorized operations and maps R matrix memory directly onto C++ pointers
#' (zero-copy on both input and output).
#'
#' @param tas    Numeric matrix (n_pixels x 12): monthly mean temperature.
#' @param tasmax Numeric matrix (n_pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (n_pixels x 12): monthly min temperature.
#' @param pr     Numeric matrix (n_pixels x 12): monthly precipitation.
#' @param ncores Integer: number of OpenMP threads (default 1).
#' @return Numeric matrix (n_pixels x 19) with one column per variable
#'   (bio01..bio19), named accordingly.  Rows with any NA input are returned
#'   as all-NA.
#' @keywords internal
bioclim_xt <- function(tas, tasmax, tasmin, pr, ncores = 1L) {
    .Call(`_xclim_bioclim_xt`, tas, tasmax, tasmin, pr, ncores)
}

#' Aggregate ERA5-Land hourly 2-m temperature to monthly statistics
#'
#' Converts an hourly temperature matrix to monthly mean temperature (tas),
#' monthly mean of daily maxima (tasmax), and monthly mean of daily minima
#' (tasmin), following the CHELSA variable convention.
#'
#' @param hourly Numeric matrix (n_pixels x n_hours): hourly 2-m temperature.
#'   Column-major layout.  n_hours must equal 24 * n_days.
#' @param n_days Integer: number of days in the month.
#' @param to_celsius Logical: if TRUE, convert Kelvin to Celsius (default
#'   FALSE, output in Kelvin matching CHELSA convention).
#' @param ncores Integer: number of OpenMP threads (default 1).
#' @return A named list with three numeric vectors of length n_pixels:
#'   \code{tas}, \code{tasmax}, \code{tasmin}.
#' @keywords internal
era5_t2m_to_monthly_cpp <- function(hourly, n_days, to_celsius = FALSE, ncores = 1L) {
    .Call(`_xclim_era5_t2m_to_monthly_cpp`, hourly, n_days, to_celsius, ncores)
}

#' Aggregate ERA5-Land hourly total precipitation to monthly total
#'
#' Sums hourly precipitation accumulations and converts from metres of water
#' to kg m⁻² month⁻¹ (equivalent to mm/month), matching the CHELSA \code{pr}
#' variable convention.
#'
#' @param hourly Numeric matrix (n_pixels x n_hours): hourly total
#'   precipitation in metres.
#' @param ncores Integer: number of OpenMP threads (default 1).
#' @return Numeric vector of length n_pixels: monthly total precipitation
#'   in kg m⁻² (mm).
#' @keywords internal
era5_tp_to_monthly_cpp <- function(hourly, ncores = 1L) {
    .Call(`_xclim_era5_tp_to_monthly_cpp`, hourly, ncores)
}

#' Unified ERA5-Land hourly-to-monthly aggregation
#'
#' Converts hourly 2-m temperature and total precipitation to the four
#' CHELSA-compatible monthly climate variables in a single parallel pass.
#'
#' @param hourly_t2m Numeric matrix (n_pixels x n_hours_t2m): hourly 2-m
#'   temperature in Kelvin.  n_hours_t2m must equal 24 * n_days.
#' @param hourly_tp Numeric matrix (n_pixels x n_hours_tp): hourly total
#'   precipitation in metres.  n_pixels must match \code{hourly_t2m}.
#' @param n_days Integer: number of days in the month.
#' @param to_celsius Logical: convert temperatures from Kelvin to Celsius?
#'   Default FALSE.
#' @param ncores Integer: number of OpenMP threads (default 1).
#' @return A named list with four numeric vectors of length n_pixels:
#'   \code{tas}, \code{tasmax}, \code{tasmin}, \code{pr}.
#' @keywords internal
era5_to_monthly_cpp <- function(hourly_t2m, hourly_tp, n_days, to_celsius = FALSE, ncores = 1L) {
    .Call(`_xclim_era5_to_monthly_cpp`, hourly_t2m, hourly_tp, n_days, to_celsius, ncores)
}

